language: python
dist: focal

python:
  - "3.12"

before_install:
  - sudo apt-get update
  - sudo apt-get install dbus-x11 libdbus-1-dev libgirepository1.0-dev pkg-config

install:
  - pip3 install dbus-python PyGObject

script:
  - ./test/generator_test.py -v
